// src/Verify.jsx
import React, { useState } from "react";
import { getIssued } from "./libs/store";
import { gatewayUrl } from "./libs/links";

export default function Verify() {
  const [cid, setCid] = useState("");
  const [out, setOut] = useState("");
  const [isError, setIsError] = useState(false);

  function handleVerify() {
    setIsError(false);

    const trimmed = cid.trim();
    if (!trimmed) {
      setIsError(true);
      setOut("Please enter a CID / certificate ID.");
      return;
    }

    const list = getIssued();
    const rec = list.find((r) => r.cid === trimmed);

    if (!rec) {
      setIsError(true);
      setOut(
        "❌ No certificate found for this CID / ID in the admin-issued records."
      );
      return;
    }

    if (rec.revoked) {
      const lines = [
        "⚠️ Certificate found, but it has been REVOKED by the admin.",
        `Student: ${rec.name}`,
        `Course: ${rec.course}`,
        `Class / Batch: ${rec.className ?? "-"}`,
        `CID / ID: ${rec.cid}`,
        `Issued At: ${new Date(rec.issuedAt * 1000).toLocaleString()}`,
      ];
      setIsError(true);
      setOut(lines.join("\n"));
      return;
    }

    const lines = [
      "✅ Certificate is VALID (based on admin-issued records).",
      `Student: ${rec.name}`,
      `Course: ${rec.course}`,
      `Class / Batch: ${rec.className ?? "-"}`,
      `CID / ID: ${rec.cid}`,
      `Issued At: ${new Date(rec.issuedAt * 1000).toLocaleString()}`,
    ];

    if (rec.imageCid) {
      lines.push(`Preview: ${gatewayUrl(rec.imageCid)}`);
    }

    setOut(lines.join("\n"));
  }

  return (
    <section className="card">
      <h2>Student – Verify Certificate</h2>
      <p>
        Enter the CID / ID printed on the certificate. Verification uses only
        the certificates generated by the teacher (Admin Issued).
      </p>

      <div className="form-row">
        <input
          className="input"
          placeholder="CID / certificate ID"
          value={cid}
          onChange={(e) => setCid(e.target.value)}
        />
        <button className="btn btn-secondary" onClick={handleVerify}>
          Verify
        </button>
      </div>

      {out && <pre className={`status ${isError ? "error" : ""}`}>{out}</pre>}
    </section>
  );
}
