// src/Verify.jsx
import React, { useState } from "react";
import { getIssued } from "./libs/store";
import { filebaseGatewayUrl } from "./ipfsClient";

export default function Verify() {
  const [inputCid, setInputCid] = useState("");
  const [result, setResult] = useState(null); // IssuedRecord | null
  const [status, setStatus] = useState("");

  function handleVerify(e) {
    e.preventDefault();
    const cid = inputCid.trim();
    if (!cid) {
      setStatus("Please enter a CID / ID.");
      setResult(null);
      return;
    }

    const list = getIssued();
    const rec = list.find((r) => r.cid === cid);

    if (!rec) {
      setStatus("❌ Certificate NOT FOUND in admin-issued records.");
      setResult(null);
      return;
    }

    if (rec.revoked) {
      setStatus("❌ Certificate has been REVOKED by admin.");
      setResult(rec);
      return;
    }

    setStatus("✅ Certificate is VALID (based on admin-issued records).");
    setResult(rec);
  }

  const rec = result;
  const cidToShow = rec ? rec.imageCid || rec.cid : "";
  const imgUrl = cidToShow ? filebaseGatewayUrl(cidToShow) : "";
  const previewLinkCid =
    rec?.imageCid || rec?.cid || inputCid.trim() || "";

  const explorerUrl =
    rec && rec.txHash
      ? `https://www.oklink.com/amoy/tx/${rec.txHash}`
      : "";

  return (
    <section style={{ padding: "1.5rem 0" }}>
      <h2>Student – Verify Certificate</h2>
      <p>
        Enter the CID / ID printed on the certificate. Verification uses only
        the certificates generated by the teacher (Admin Issued).
      </p>

      <form onSubmit={handleVerify} style={{ marginBottom: "1rem" }}>
        <input
          style={{ width: "360px", marginRight: "0.5rem" }}
          type="text"
          value={inputCid}
          onChange={(e) => setInputCid(e.target.value)}
          placeholder="Paste CID / ID here..."
        />
        <button type="submit">Verify</button>
      </form>

      {status && (
        <div
          style={{
            marginBottom: "1rem",
            padding: "0.75rem",
            borderRadius: "8px",
            border: "1px solid #ddd",
            background: "#fafafa",
          }}
        >
          {status}
        </div>
      )}

      {rec && (
        <div
          style={{
            border: "1px solid #ddd",
            borderRadius: "8px",
            padding: "1rem",
            display: "flex",
            gap: "1rem",
          }}
        >
          <div>
            {imgUrl ? (
              <img
                src={imgUrl}
                alt="Certificate preview"
                style={{
                  width: "200px",
                  height: "200px",
                  objectFit: "cover",
                  borderRadius: "4px",
                  border: "1px solid #ddd",
                }}
                onError={(e) => {
                  (e.currentTarget).style.display = "none";
                }}
              />
            ) : (
              <div
                style={{
                  width: "200px",
                  height: "200px",
                  borderRadius: "4px",
                  border: "1px solid #eee",
                }}
              />
            )}
            {previewLinkCid && (
              <div style={{ marginTop: "0.5rem", fontSize: "0.8rem" }}>
                Preview from IPFS:
                <br />
                <a
                  href={filebaseGatewayUrl(previewLinkCid)}
                  target="_blank"
                  rel="noreferrer"
                >
                  {filebaseGatewayUrl(previewLinkCid)}
                </a>
              </div>
            )}
          </div>

          <div>
            <p>
              <strong>Student:</strong> {rec.name}
            </p>
            <p>
              <strong>Course:</strong> {rec.course}
            </p>
            <p>
              <strong>Class / Batch:</strong> {rec.className || "-"}
            </p>
            <p>
              <strong>CID / ID:</strong> {rec.cid}
            </p>
            <p>
              <strong>Issued At:</strong>{" "}
              {new Date(rec.issuedAt * 1000).toLocaleString()}
            </p>
            {explorerUrl && (
              <p>
                <strong>Blockchain Tx:</strong>{" "}
                <a href={explorerUrl} target="_blank" rel="noreferrer">
                  View on Explorer
                </a>
              </p>
            )}
          </div>
        </div>
      )}
    </section>
  );
}
